---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-12-10 - 10:01:25 +0000
  labels:
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/name: slightly-disordered-lemur
  name: slightly-disordered-lemur
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-12-10 - 10:01:25 +0000
  labels:
    app.kubernetes.io/name: slightly-disordered-lemur
    app.kubernetes.io/version: "1.0"
  name: slightly-disordered-lemur
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: slightly-disordered-lemur
    app.kubernetes.io/version: "1.0"
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: randomkillcontroller-cluster-role
rules:
  - apiGroups:
      - yap.onepoint.com
    resources:
      - randomkillrequests
      - randomkillrequests/status
      - randominvasionrequests
      - randominvasionrequests/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups: [ "" ]
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups: [ "" ]
    resources:
      - pods/exec
      - serviceaccounts
      - services
    verbs:
      - create
      - update
      - get
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources:
      - clusterroles
      - rolebindings
    verbs:
      - create
      - update
      - get
  - apiGroups: [ "events.k8s.io" ]
    resources:
      - events
    verbs:
      - create
      - update
      - get
  - apiGroups: [ "apps" ]
    resources:
      - deployments
    verbs:
      - create
      - update
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: randomkillcontroller-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: randomkillcontroller-cluster-role
subjects:
  - kind: ServiceAccount
    name: slightly-disordered-lemur
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-12-10 - 10:01:25 +0000
  labels:
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/name: slightly-disordered-lemur
  name: slightly-disordered-lemur
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: "1.0"
      app.kubernetes.io/name: slightly-disordered-lemur
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2021-12-10 - 10:01:25 +0000
      labels:
        app.kubernetes.io/version: "1.0"
        app.kubernetes.io/name: slightly-disordered-lemur
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/jtama/slightly-disordered-lemur:1.0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: slightly-disordered-lemur
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: slightly-disordered-lemur
