= slightly-disordered-lemur Project
:icons: font
:source-highlighter: coderay

This project uses Quarkus, the Supersonic Subatomic Java Framework.

It demonstrates how to develop a K8S operator using the quarkus-operator-sdk.

If you want to learn more about Quarkus, please visit its website: https://quarkus.io/ .

[IMPORTANT]
====
 This cannot be build to native to due to limitations in GraalVM that isn't compatible with record usage at the time being.
====

== Integration testing

Testing is done using `@WithKubernetesTestServer` annotation which allows us to mock a distant K8S server  and pilot it's behaviours.


== Running the application in dev mode

Before running your application in dev mode, make sure to connect to a K8S cluster and eventually specify the default namespace to use.

[source,bash]
----
kubectl config set-context --current --namespace=
----



You can run your application in dev mode that enables live coding using:
[source,bash]
----
./mvnw compile quarkus:dev
----

[TIP]
====
Quarkus now ships with a Dev UI, which is available in dev mode only at http://localhost:8080/q/dev/.
====

